name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/docs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm install -g docsify-cli
      - name: Build docs
        run: |
          mkdir -p _site
          cp -r docs/* _site/
          cp README.md _site/
          cat > _site/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>AutoSpectra MCP Server</title>
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
            <meta name="description" content="Browser automation and testing with MCP protocol">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
            <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
          </head>
          <body>
            <div id="app"></div>
            <script>
              window.$docsify = {
                name: 'AutoSpectra MCP Server',
                repo: 'https://github.com/autospectra/autospectra-mcp-server',
                loadSidebar: true,
                subMaxLevel: 3,
                auto2top: true
              }
            </script>
            <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
            <script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-javascript.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-typescript.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-json.min.js"></script>
          </body>
          </html>
          EOL
          
          cat > _site/_sidebar.md << 'EOL'
          * [Home](/)
          * [Cloud Deployment](CLOUD_DEPLOYMENT.md)
          * [Smithery Integration](smithery-integration.md)
          * [Quick Reference](QUICK_REFERENCE.md)
          EOL
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
